### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by deepbodra97** [alexvlis/extractive-document-summarization#7]
It seems that the dataset is no longer publicly available. Also, the link to download the dataset has crashed. Can someone share the dataset or an alternative dataset so that the code need not be modified drastically? I am kind of new to ML so having a hard time preprocessing.

**Comment by alexvlis** [comment]
I think the website is not working because of the government shutdown. If I remember correctly you have to fill in a form to download the dataset. Maybe you can wait for the government shutdown to be resolved, if that is an option for you.

**Comment by deepbodra97** [comment]
Yes, I emailed them but I got an autogenerated response saying that the government has shutdown the website. If possible, can someone share the dataset? maybe by google drive or any other means

**Comment by deepbodra97** [comment]
Finally, I found the DUC2004 dataset. Check out this repo:
https://github.com/NightFury13/TextSummarizer/tree/master/DUC-2004
